animals = ['bear', 'python', 'peacock', 'kangaroo', 'whale', 'platypus']

print "The animal at 1 is %s." % animals[1]
print "The third animal(3rd) is %s." % animals[2]
print "The first animal(1st) is %s." % animals[0]
print "The animal at 3 is %s." % animals[3]
print "The fifth animal(5th) is %s." % animals[4]
print "The animal at 2 is %s." % animals[2]
print "The sixth(6th) animal is %s." % animals[5]
print "The animal at 4 is %s." % animals[4]
